// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC12r6AJwXsTy_7L4RrS6BdHRM9KDBto-4',
    appId: '1:708265003002:web:de408d2e66a6d508cd0643',
    messagingSenderId: '708265003002',
    projectId: 'app-inventario-ventas-3419a',
    authDomain: 'app-inventario-ventas-3419a.firebaseapp.com',
    storageBucket: 'app-inventario-ventas-3419a.firebasestorage.app',
    measurementId: 'G-43HMXTJRD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABiydTnZqR1NgiPM5AQandS4Cpf9XVddA',
    appId: '1:708265003002:android:affd50d70862ef16cd0643',
    messagingSenderId: '708265003002',
    projectId: 'app-inventario-ventas-3419a',
    storageBucket: 'app-inventario-ventas-3419a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdamrhQAOBiFuXnGTP9DA4bsFfVkCyVpw',
    appId: '1:708265003002:ios:0f2a022ff1683f0ecd0643',
    messagingSenderId: '708265003002',
    projectId: 'app-inventario-ventas-3419a',
    storageBucket: 'app-inventario-ventas-3419a.firebasestorage.app',
    iosBundleId: 'com.example.appInventarioVentas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdamrhQAOBiFuXnGTP9DA4bsFfVkCyVpw',
    appId: '1:708265003002:ios:0f2a022ff1683f0ecd0643',
    messagingSenderId: '708265003002',
    projectId: 'app-inventario-ventas-3419a',
    storageBucket: 'app-inventario-ventas-3419a.firebasestorage.app',
    iosBundleId: 'com.example.appInventarioVentas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC12r6AJwXsTy_7L4RrS6BdHRM9KDBto-4',
    appId: '1:708265003002:web:e4012ab88fc3a7b5cd0643',
    messagingSenderId: '708265003002',
    projectId: 'app-inventario-ventas-3419a',
    authDomain: 'app-inventario-ventas-3419a.firebaseapp.com',
    storageBucket: 'app-inventario-ventas-3419a.firebasestorage.app',
    measurementId: 'G-0XVXJJM6BD',
  );
}
